const errorCodes = [
    {code: 100, errorCode: 100, message: 'Continue'},
    {code: 101, errorCode: 101, message: 'Switching Protocols'},
    {code: 102, errorCode: 102, message: 'Processing'},
    {code: 200, errorCode: 200, message: 'OK'},
    {code: 201, errorCode: 201, message: 'Created'},
    {code: 202, errorCode: 202, message: 'Accepted'},
    {code: 203, errorCode: 203, message: 'Non-Authoritative Information'},
    {code: 204, errorCode: 204, message: 'No Content'},
    {code: 205, errorCode: 205, message: 'Reset Content'},
    {code: 206, errorCode: 206, message: 'Partial Content'},
    {code: 207, errorCode: 207, message: 'Multi-Status'},
    {code: 300, errorCode: 300, message: 'Multiple Choices'},
    {code: 301, errorCode: 301, message: 'Moved Permanently'},
    {code: 302, errorCode: 302, message: 'Moved Temporarily'},
    {code: 303, errorCode: 303, message: 'See Other'},
    {code: 304, errorCode: 304, message: 'Not Modified'},
    {code: 305, errorCode: 305, message: 'Use Proxy'},
    {code: 307, errorCode: 307, message: 'Temporary Redirect'},
    {code: 308, errorCode: 401, message: 'Incorrect email or password...'},
    {code: 309, errorCode: 400, message: 'You have an ongoing transaction'},
    {code: 400, errorCode: 400, message: 'Bad Request'},
    {code: 401, errorCode: 401, message: 'Unauthorized'},
    {code: 402, errorCode: 402, message: 'Payment Required'},
    {code: 403, errorCode: 403, message: 'Forbidden'},
    {code: 404, errorCode: 404, message: 'Not Found'},
    {code: 405, errorCode: 405, message: 'Method Not Allowed'},
    {code: 406, errorCode: 406, message: 'Not Acceptable'},
    {code: 407, errorCode: 407, message: 'Proxy Authentication Required'},
    {code: 408, errorCode: 408, message: 'Request Time-out'},
    {code: 409, errorCode: 409, message: 'Conflict'},
    {code: 410, errorCode: 410, message: 'Gone'},
    {code: 411, errorCode: 411, message: 'Length Required'},
    {code: 412, errorCode: 412, message: 'Precondition Failed'},
    {code: 413, errorCode: 413, message: 'Request Entity Too Large'},
    {code: 414, errorCode: 414, message: 'Request-URI Too Large'},
    {code: 415, errorCode: 415, message: 'Unsupported Media Type'},
    {code: 416, errorCode: 416, message: 'Requested Range Not Satisfiable'},
    {code: 417, errorCode: 417, message: 'Expectation Failed'},
    {code: 418, errorCode: 418, message: 'I\'m a teapot'},
    {code: 422, errorCode: 422, message: 'Unprocessable Entity'},
    {code: 423, errorCode: 423, message: 'Locked'},
    {code: 424, errorCode: 424, message: 'Failed Dependency'},
    {code: 425, errorCode: 425, message: 'Too Early'},
    {code: 426, errorCode: 426, message: 'Upgrade Required'},
    {code: 428, errorCode: 428, message: 'Precondition Required'},
    {code: 429, errorCode: 429, message: 'Too Many Requests'},
    {code: 431, errorCode: 431, message: 'Request Header Fields Too Large'},
    {code: 451, errorCode: 451, message: 'Unavailable For Legal Reasons'},
    {code: 498, errorCode: 498, message: 'Invalid Token'},
    {code: 500, errorCode: 500, message: 'Internal Server Error'},
    {code: 501, errorCode: 501, message: 'Not Implemented'},
    {code: 502, errorCode: 502, message: 'Bad Gateway'},
    {code: 503, errorCode: 503, message: 'Service Unavailable'},
    {code: 504, errorCode: 504, message: 'Gateway Time-out'},
    {code: 505, errorCode: 505, message: 'HTTP Version Not Supported'},
    {code: 506, errorCode: 506, message: 'Variant Also Negotiates'},
    {code: 507, errorCode: 507, message: 'Insufficient Storage'},
    {code: 509, errorCode: 509, message: 'Bandwidth Limit Exceeded'},
    {code: 510, errorCode: 510, message: 'Not Extended'},
    {code: 511, errorCode: 511, message: 'Network Authentication Required'}
];

export {errorCodes};